item {
    id: 1
    name: 'Aloe aristata'
}

item {
    id: 2
    name: 'Aloe barbadensis'
}

item {
    id: 3
    name: 'Aloe chinensis'
}

item {
    id: 4
    name: 'Aloe donnie'
}

item {
    id: 5
    name: 'Aloe doran'
}

item {
    id: 6
    name: 'Aloe jucunda'
}

